const MAX_SEND_TRANSACTION_RETRIES = 5;

const ANTI_MEV_ENABLED_SLIPPAGE = 5;

const MESSAGE_DELETE_DELAY = 30_000;

const MAX_NUMBER_OF_WALLETS = 10;

const WITHDRAWAL_BONUS_VALUE = 0.3;

exports.MAX_SEND_TRANSACTION_RETRIES = MAX_SEND_TRANSACTION_RETRIES;
exports.ANTI_MEV_ENABLED_SLIPPAGE = ANTI_MEV_ENABLED_SLIPPAGE;
exports.MESSAGE_DELETE_DELAY = MESSAGE_DELETE_DELAY;
exports.MAX_NUMBER_OF_WALLETS = MAX_NUMBER_OF_WALLETS;
exports.WITHDRAWAL_BONUS_VALUE = WITHDRAWAL_BONUS_VALUE;